export const COUNTRIES = [
  { value: "1", label: "Afghanistan" },
  { value: "2", label: "Albania" },
  { value: "3", label: "Algeria" },
  { value: "4", label: "Andorra" },
  { value: "5", label: "Angola" },
  { value: "6", label: "Antigua and Barbuda" },
  { value: "7", label: "Argentina" },
  { value: "8", label: "Armenia" },
  { value: "9", label: "Australia" },
  { value: "10", label: "Austria" },
  { value: "11", label: "Azerbaijan" },
  { value: "12", label: "Bahamas" },
  { value: "13", label: "Bahrain" },
  { value: "14", label: "Bangladesh" },
  { value: "15", label: "Barbados" },
  { value: "16", label: "Belarus" },
  { value: "17", label: "Belgium" },
  { value: "18", label: "Belize" },
  { value: "19", label: "Benin" },
  { value: "20", label: "Bhutan" },
  { value: "21", label: "Bolivia" },
  { value: "22", label: "Bosnia and Herzegovina" },
  { value: "23", label: "Botswana" },
  { value: "24", label: "Brazil" },
  { value: "25", label: "Brunei" },
  { value: "26", label: "Bulgaria" },
  { value: "27", label: "Burkina Faso" },
  { value: "28", label: "Burundi" },
  { value: "29", label: "Cabo Verde" },
  { value: "30", label: "Cambodia" },
  { value: "31", label: "Cameroon" },
  { value: "32", label: "Canada" },
  { value: "33", label: "Central African Republic" },
  { value: "34", label: "Chad" },
  { value: "35", label: "Chile" },
  { value: "36", label: "China" },
  { value: "37", label: "Colombia" },
  { value: "38", label: "Comoros" },
  { value: "39", label: "Congo" },
  { value: "40", label: "Costa Rica" },
  { value: "41", label: "Croatia" },
  { value: "42", label: "Cuba" },
  { value: "43", label: "Cyprus" },
  { value: "44", label: "Czechia" },
  { value: "45", label: "Denmark" },
  { value: "46", label: "Djibouti" },
  { value: "47", label: "Dominica" },
  { value: "48", label: "Dominican Republic" },
  { value: "49", label: "East Timor" },
  { value: "50", label: "Ecuador" },
  { value: "51", label: "Egypt" },
  { value: "52", label: "El Salvador" },
  { value: "53", label: "Equatorial Guinea" },
  { value: "54", label: "Eritrea" },
  { value: "55", label: "Estonia" },
  { value: "56", label: "Eswatini" },
  { value: "57", label: "Ethiopia" },
  { value: "58", label: "Fiji" },
  { value: "59", label: "Finland" },
  { value: "60", label: "France" },
  { value: "61", label: "Gabon" },
  { value: "62", label: "Gambia" },
  { value: "63", label: "Georgia" },
  { value: "64", label: "Germany" },
  { value: "65", label: "Ghana" },
  { value: "66", label: "Greece" },
  { value: "67", label: "Grenada" },
  { value: "68", label: "Guatemala" },
  { value: "69", label: "Guinea" },
  { value: "70", label: "Guinea-Bissau" },
  { value: "71", label: "Guyana" },
  { value: "72", label: "Haiti" },
  { value: "73", label: "Honduras" },
  { value: "74", label: "Hungary" },
  { value: "75", label: "Iceland" },
  { value: "76", label: "India" },
  { value: "77", label: "Indonesia" },
  { value: "78", label: "Iran" },
  { value: "79", label: "Iraq" },
  { value: "80", label: "Ireland" },
  { value: "81", label: "Italy" },
  { value: "82", label: "Jamaica" },
  { value: "83", label: "Japan" },
  { value: "84", label: "Jordan" },
  { value: "85", label: "Kazakhstan" },
  { value: "86", label: "Kenya" },
  { value: "87", label: "Kiribati" },
  { value: "88", label: "Korea, North" },
  { value: "89", label: "Korea, South" },
  { value: "90", label: "Kuwait" },
  { value: "91", label: "Kyrgyzstan" },
  { value: "92", label: "Laos" },
  { value: "93", label: "Latvia" },
  { value: "94", label: "Lebanon" },
  { value: "95", label: "Lesotho" },
  { value: "96", label: "Liberia" },
  { value: "97", label: "Libya" },
  { value: "98", label: "Liechtenstein" },
  { value: "99", label: "Lithuania" },
  { value: "100", label: "Luxembourg" },
  { value: "101", label: "Madagascar" },
  { value: "102", label: "Malawi" },
  { value: "103", label: "Malaysia" },
  { value: "104", label: "Maldives" },
  { value: "105", label: "Mali" },
  { value: "106", label: "Malta" },
  { value: "107", label: "Marshall Islands" },
  { value: "108", label: "Mauritania" },
  { value: "109", label: "Mauritius" },
  { value: "110", label: "Mexico" },
  { value: "111", label: "Micronesia" },
  { value: "112", label: "Moldova" },
  { value: "113", label: "Monaco" },
  { value: "114", label: "Mongolia" },
  { value: "115", label: "Montenegro" },
  { value: "116", label: "Morocco" },
  { value: "117", label: "Mozambique" },
  { value: "118", label: "Myanmar" },
  { value: "119", label: "Namibia" },
  { value: "120", label: "Nauru" },
  { value: "121", label: "Nepal" },
  { value: "122", label: "Netherlands" },
  { value: "123", label: "New Zealand" },
  { value: "124", label: "Nicaragua" },
  { value: "125", label: "Niger" },
  { value: "126", label: "Nigeria" },
  { value: "127", label: "North Macedonia" },
  { value: "128", label: "Norway" },
  { value: "129", label: "Oman" },
  { value: "130", label: "Pakistan" },
  { value: "131", label: "Palau" },
  { value: "132", label: "Panama" },
  { value: "133", label: "Papua New Guinea" },
  { value: "134", label: "Paraguay" },
  { value: "135", label: "Peru" },
  { value: "136", label: "Philippines" },
  { value: "137", label: "Poland" },
  { value: "138", label: "Portugal" },
  { value: "139", label: "Qatar" },
  { value: "140", label: "Romania" },
  { value: "141", label: "Russia" },
  { value: "142", label: "Rwanda" },
  { value: "143", label: "Saint Kitts and Nevis" },
  { value: "144", label: "Saint Lucia" },
  { value: "145", label: "Saint Vincent and the Grenadines" },
  { value: "146", label: "Samoa" },
  { value: "147", label: "San Marino" },
  { value: "148", label: "Sao Tome and Principe" },
  { value: "149", label: "Saudi Arabia" },
  { value: "150", label: "Senegal" },
  { value: "151", label: "Serbia" },
  { value: "152", label: "Seychelles" },
  { value: "153", label: "Sierra Leone" },
  { value: "154", label: "Singapore" },
  { value: "155", label: "Slovakia" },
  { value: "156", label: "Slovenia" },
  { value: "157", label: "Solomon Islands" },
  { value: "158", label: "Somalia" },
  { value: "159", label: "South Africa" },
  { value: "160", label: "South Sudan" },
  { value: "161", label: "Spain" },
  { value: "162", label: "Sri Lanka" },
  { value: "163", label: "Sudan" },
  { value: "164", label: "Suriname" },
  { value: "165", label: "Sweden" },
  { value: "166", label: "Switzerland" },
  { value: "167", label: "Syria" },
  { value: "168", label: "Taiwan" },
  { value: "169", label: "Tajikistan" },
  { value: "170", label: "Tanzania" },
  { value: "171", label: "Thailand" },
  { value: "172", label: "Togo" },
  { value: "173", label: "Tonga" },
  { value: "174", label: "Trinidad and Tobago" },
  { value: "175", label: "Tunisia" },
  { value: "176", label: "Turkey" },
  { value: "177", label: "Turkmenistan" },
  { value: "178", label: "Tuvalu" },
  { value: "179", label: "Uganda" },
  { value: "180", label: "Ukraine" },
  { value: "181", label: "United Arab Emirates" },
  { value: "182", label: "United Kingdom" },
  { value: "183", label: "Uruguay" },
  { value: "184", label: "Uzbekistan" },
  { value: "185", label: "Vanuatu" },
  { value: "186", label: "Vatican City" },
  { value: "187", label: "Venezuela" },
  { value: "188", label: "Vietnam" },
  { value: "189", label: "Yemen" },
  { value: "190", label: "Zambia" },
  { value: "191", label: "Zimbabwe" },
];
